// Mocks generated by Mockito 5.4.6 from annotations
// in matchtcg_app/test/data/repositories/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:matchtcg_app/data/models/auth_requests.dart' as _i6;
import 'package:matchtcg_app/data/services/auth_api_service.dart' as _i4;
import 'package:matchtcg_app/data/services/secure_storage_service.dart' as _i7;
import 'package:matchtcg_app/domain/entities/auth_response.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpResponse_1<T> extends _i1.SmartFake
    implements _i3.HttpResponse<T> {
  _FakeHttpResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApiService extends _i1.Mock implements _i4.AuthApiService {
  MockAuthApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.AuthResponse> login(_i6.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(this, Invocation.method(#login, [request])),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<_i2.AuthResponse> register(_i6.RegisterRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<_i2.AuthResponse> refresh(_i6.RefreshRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#refresh, [request]),
            returnValue: _i5.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(this, Invocation.method(#refresh, [request])),
            ),
          )
          as _i5.Future<_i2.AuthResponse>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.HttpResponse<dynamic>> getGoogleOAuthUrl() =>
      (super.noSuchMethod(
            Invocation.method(#getGoogleOAuthUrl, []),
            returnValue: _i5.Future<_i3.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_1<dynamic>(
                this,
                Invocation.method(#getGoogleOAuthUrl, []),
              ),
            ),
          )
          as _i5.Future<_i3.HttpResponse<dynamic>>);

  @override
  _i5.Future<_i3.HttpResponse<dynamic>> getAppleOAuthUrl() =>
      (super.noSuchMethod(
            Invocation.method(#getAppleOAuthUrl, []),
            returnValue: _i5.Future<_i3.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_1<dynamic>(
                this,
                Invocation.method(#getAppleOAuthUrl, []),
              ),
            ),
          )
          as _i5.Future<_i3.HttpResponse<dynamic>>);
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i7.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> write(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#write, [key, value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> read(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#read, [key]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> delete(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [key]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveAccessToken, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> saveRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveRefreshToken, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> saveUserInfo(Map<String, dynamic>? userInfo) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserInfo, [userInfo]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>?> getUserInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getUserInfo, []),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> clearAuthData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAuthData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
