name: matchtcg_app
description: "MatchTCG Flutter App - Trading Card Game event discovery and community management"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^16.2.1

  # HTTP & API
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0

  # Storage
  flutter_secure_storage: ^10.0.0-beta.4
  shared_preferences: ^2.3.2

  # Maps
  maplibre_gl: ^0.22.0

  # Internationalization
  intl: ^0.19.0

  # UI & Theming
  cupertino_icons: ^1.0.8

  # Utilities
  equatable: ^2.0.5
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  flutter_native_timezone: ^2.0.0
  path_provider: ^2.1.4
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  retrofit_generator: ^9.7.0
  riverpod_generator: ^2.4.3
  json_serializable: ^6.8.0

  # Testing
  mockito: ^5.4.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/brands_logo/
    - assets/icons/

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
